### ISSUE TITLE
Compile Error: Assigning to arguments in strict mode

### ISSUE THREAD

**Issue by jey-nandakumar** [Stamplay/stamplay-js-sdk#17]
I get this error when I try to import Stamplay using browersify.

[Compile Error] 
stamplay.js: Assigning to arguments in strict mode (3192:4) while parsing file dist/stamplay.js

**Comment by criroselli** [comment]
Hi there,
can I ask you, why you use browserify with this sdk? 

Let me know

**Comment by chiefGui** [comment]
I will get myself into the conversation @criroselli because I want to use Stamplay through a module loader as webpack as well.

At first, all my architecture is CommonJS based, which means that Stamplay—that is not CommonJS ready—is the only library breaking my entire foundation.

Secondly, I used Stamplay to create proof-of-concept-applications a lot. The major part of those applications was based in CommonJS as well. When building, I needed to give to the users three files: `index.html`, `app.js` and `stamplay-sdk.js` _or_ loading the SDK through the CDN.

Thirdly and not (that) important, the Stamplay's scope is the `window` and modules should not belong to it.

Anyway, this doesn't bother me at all. Its features worth it. _But please, you could consider giving us an AMD/CommonJS-ready version, huh?_
